### PR TITLE
feat: added CocoaPods support

### PR DESCRIPTION
**Pull request by soumyamahunt**

### CODE REVIEW

**Comment by Ariandr** [comment]
Hi @soumyamahunt 
Are there issues with Cocoapods integration?

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt 
> Are there issues with Cocoapods integration?

Hi @Ariandr, Cocoapods doesn't support macros unlike Swift package.

**Comment by Ariandr** [comment]
@soumyamahunt 
I see, it's a shame. Hopefully soon the support will be added so that you can add it to Cocoapods.

**Comment by Ariandr** [comment]
Hi @soumyamahunt 
Thank you for adding the CocoaPods support! 🥳
Was it hard to do?
Or did they add a workaround for this?

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt 
> Thank you for adding the CocoaPods support! 🥳
> Was it hard to do?
> Or did they add a workaround for this?

No workaround has been added by CocoaPods. I found a workaround using existing features which was quite hard to test, especially with CocoaPods taking around 1 hour to run linting.

I am writing a medium post on the workaround that other macro authors can use. Stay tuned.

**Comment by Ariandr** [comment]
Great work!

**Pull request merged**
